language: generic
os:
- linux
- osx
env:
  matrix:
  - PYTHON="3.8"
  - PYTHON="3.7"
  - PYTHON="3.6"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
sudo: false
jobs:
  - stage: docs
    os: linux
    install:
    - pip install -e .
    - pip install -r requirements-docs.txt
    script:
    - make -C docs clean html

  include:
  - stage: deploy
    if: tag =~ v.*$
    script: skip
    os: linux
    deploy:
      on:
        all_branches: true
      provider: pypi
      user: mcflugen
      password:
        secure: jMgyzEirqv0zFAW5ETWMkSsbO7Ei26Hx3QCiNKwKZJqotujuEoXcErEhOkD4kGChpYgK9qXtQ3+HmPqOPr6D26amGLIWBB1l1upVdf1ijPX/a/tUwSmFrdVO31527VtVjqc4f/rVIyVJ6HtdP76XoCBNPjHRTemyqKM9FrUa0LTNR+SENQdKhUAbtr5MW5jfNlDIVUoWkPDuNTd/Pp1UWzSHCr9WY2pxNNM3HHXFgLDUbf5WMIMsjHUw2TWs2JqGQvs/30W40LsSyYNO/KKqJYLH5T0qiHebalUcs3ExRnlxPys1BnE6WSdILv+Rw5xrOK/1xD9VPqXzs/bP0KxPQMxbHwr7/9hZF2XjYSXxg0enLwgFZ7FwkyTJBXo+lp07GJ/7TtleLx2VCUcKlOdgfxqWvX7PJvyIf6DSUidGk33AW5+25T3bddj7KP/OmSSidA10Bsai/amHhRqkP37giw9oKCmKvVhv1oH1xOi5ymEsyaoGYnNvUz+MqLySSVESTC8zUlM29vftpKse2a63QigP+22W4VMLfQp+qA5p7ou6YeR+i04SkqfM+XJyEJMqV9FPFBGx9pNT2SmCPUDyOh7kNRXcrRxz4qpIGxl7pFh2X/+8G7Ou1Jv3iMchg7zzMIX7eJ35p7RkAMRIaaPN0R8HPxAXpf9GYciGmcvlGr0=
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n _testing python=$PYTHON
- source activate _testing
- conda info -a && conda list
install:
- pip install .
script:
- rafem --version
- rafem --help
- rafem show --help
- rafem setup --help
- rafem run --help
- rafem plot --help
- rafem show rafem
- mkdir example && rafem --cd example setup run
after_success: coveralls
